language: node_js
node_js: stable

before_install:
  - npm install -g hexo-cli

# S: Build Lifecycle
install:
  - npm install


#before_script:
 # - npm install -g gulp

script:
  - hexo clean
  - hexo g

after_script:
  - cd ./public
  - git init
  - git config user.name "Zgxh"
  - git config user.email "1227814546@qq.com"
  - git add .
  - git commit -m "Add new articles"
  - git push --force --quiet "https://${zgxhblog}@${GH_REF}" master:master
# E: Build LifeCycle

branches:
  only:
    - dev
env:
 global:
   - GH_REF: github.com/Zgxh/Zgxh.github.io.git
   - secure: ebdf0c7f3fd7352fa7b40d9ff6bc54980011ff33